general.import = [
    "~/.config/alacritty/keybinds.toml",
    "~/.config/alacritty/colors.toml"
]

[window]
decorations = "none"
dynamic_title = false
dynamic_padding = false
opacity = 0.85
padding = { x = 0, y = 0 }
startup_mode = "Maximized"

[font]
size = 8.0
normal      = { family = "NotoMono Nerd Font Mono", style = "Medium" }
bold        = { family = "NotoMono Nerd Font Mono", style = "Bold" }
bold_italic = { family = "NotoMono Nerd Font Mono", style = "Bold Italic" }
italic      = { family = "NotoMono Nerd Font Mono", style = "Italic" }

[selection]
save_to_clipboard = true

[cursor]
style = { blinking = "Off", shape = "Block" }

[mouse]
hide_when_typing = true

