[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.search.focused_match]
background = "#ffbb00"
foreground = "#806060"

[colors.search.matches]
background = "#806060"
foreground = "#ffbb00"

[colors.hints.start]
background = "#000000"
foreground = "#ffffff"

[colors.hints.end]
background = "#000000"
foreground = "#ffffff"

[colors.line_indicator]
background = "#000000"
foreground = "#ffffff"

[colors.footer_bar]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

