[keyboard]
bindings = [
{                       key = "Paste",                                  action = "Paste" },
{                       key = "Copy",                                   action = "Copy" },
{                       key = "C",              mods = "Control|Shift", action = "Copy" },
{                       key = "Key0",           mods = "Control",       action = "ResetFontSize" },
{                       key = "Equals",         mods = "Control",       action = "IncreaseFontSize" },
{                       key = "Minus",          mods = "Control",       action = "DecreaseFontSize" },
{                       key = "L",              mods = "Control",       action = "ClearLogNotice" },
{ mode = "~Vi|~Search", key = "L",              mods = "Control",        chars = "\f" },
{ mode = "Vi|~Search",  key = "C",              mods = "Control|Shift", action = "ClearSelection" },
{ mode = "~Vi",         key = "V",              mods = "Control|Shift", action = "Paste" },
{ mode = "Vi|~Search",  key = "Space",          mods = "Shift|Control", action = "ScrollToBottom" },
{ mode = "Vi|~Search",  key = "Escape",                                 action = "ClearSelection" },
{ mode = "Vi|~Search",  key = "I",                                      action = "ScrollToBottom" },
{ mode = "Vi|~Search",  key = "I",                                      action = "ToggleViMode" },
{ mode = "Vi|~Search",  key = "C",              mods = "Control",       action = "ToggleViMode" },
{ mode = "Vi|~Search",  key = "Y",              mods = "Control",       action = "ScrollLineUp" },
{ mode = "Vi|~Search",  key = "E",              mods = "Control",       action = "ScrollLineDown" },
{ mode = "Vi|~Search",  key = "G",                                      action = "ScrollToTop" },
{ mode = "Vi|~Search",  key = "G",              mods = "Shift",         action = "ScrollToBottom" },
{ mode = "Vi|~Search",  key = "B",              mods = "Control",       action = "ScrollPageUp" },
{ mode = "Vi|~Search",  key = "F",              mods = "Control",       action = "ScrollPageDown" },
{ mode = "Vi|~Search",  key = "U",              mods = "Control",       action = "ScrollHalfPageUp" },
{ mode = "Vi|~Search",  key = "D",              mods = "Control",       action = "ScrollHalfPageDown" },
{ mode = "Vi|~Search",  key = "Y",                                      action = "Copy" },
{ mode = "Vi|~Search",  key = "Y",                                      action = "ClearSelection" },
{ mode = "Vi|~Search",  key = "Copy",                                   action = "ClearSelection" },
{ mode = "Vi|~Search",  key = "V",                                      action = "ToggleNormalSelection" },
{ mode = "Vi|~Search",  key = "V",              mods = "Shift",         action = "ToggleLineSelection" },
{ mode = "Vi|~Search",  key = "V",              mods = "Control",       action = "ToggleBlockSelection" },
{ mode = "Vi|~Search",  key = "V",              mods = "Alt",           action = "ToggleSemanticSelection" },
{ mode = "Vi|~Search",  key = "Return",                                 action = "Open" },
{ mode = "Vi|~Search",  key = "K",                                      action = "Up" },
{ mode = "Vi|~Search",  key = "J",                                      action = "Down" },
{ mode = "Vi|~Search",  key = "H",                                      action = "Left" },
{ mode = "Vi|~Search",  key = "L",                                      action = "Right" },
{ mode = "Vi|~Search",  key = "Key0",                                   action = "First" },
{ mode = "Vi|~Search",  key = "Key4",           mods = "Shift",         action = "Last" },
{ mode = "Vi|~Search",  key = "Key6",           mods = "Shift",         action = "FirstOccupied" },
{ mode = "Vi|~Search",  key = "H",              mods = "Shift",         action = "High" },
{ mode = "Vi|~Search",  key = "M",              mods = "Shift",         action = "Middle" },
{ mode = "Vi|~Search",  key = "L",              mods = "Shift",         action = "Low" },
{ mode = "Vi|~Search",  key = "B",                                      action = "SemanticLeft" },
{ mode = "Vi|~Search",  key = "W",                                      action = "SemanticRight" },
{ mode = "Vi|~Search",  key = "E",                                      action = "SemanticRightEnd" },
{ mode = "Vi|~Search",  key = "B",              mods = "Shift",         action = "WordLeft" },
{ mode = "Vi|~Search",  key = "W",              mods = "Shift",         action = "WordRight" },
{ mode = "Vi|~Search",  key = "E",              mods = "Shift",         action = "WordRightEnd" },
{ mode = "Vi|~Search",  key = "Key5",           mods = "Shift",         action = "Bracket" },
{ mode = "Vi|~Search",  key = "Slash",                                  action = "SearchForward" },
{ mode = "Vi|~Search",  key = "Slash",          mods = "Shift",         action = "SearchBackward" },
{ mode = "Vi|~Search",  key = "N",                                      action = "SearchNext" },
{ mode = "Vi|~Search",  key = "N",              mods = "Shift",         action = "SearchPrevious" },
{ mode = "Search|~Vi",  key = "Return",         mods = "Shift",         action = "SearchFocusPrevious" },
{ mode = "Search|~Vi",  key = "Return",                                 action = "SearchFocusNext" },
{ mode = "Search|Vi",   key = "Return",                                 action = "SearchConfirm" },
{ mode = "Search",      key = "Escape",                                 action = "SearchCancel" },
{ mode = "Search",      key = "C",              mods = "Control",       action = "SearchCancel" },
{ mode = "Search",      key = "U",              mods = "Control",       action = "SearchClear" },
{ mode = "Search",      key = "W",              mods = "Control",       action = "SearchDeleteWord" },
{ mode = "Search",      key = "P",              mods = "Control",       action = "SearchHistoryPrevious" },
{ mode = "Search",      key = "N",              mods = "Control",       action = "SearchHistoryNext" },
{ mode = "Search",      key = "Up",                                     action = "SearchHistoryPrevious" },
{ mode = "Search",      key = "Down",                                   action = "SearchHistoryNext" },
{ mode = "~Search",     key = "Space",          mods = "Shift|Control", action = "ToggleViMode" },
]
