require'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "asm",
        "bash",
        "c",
        "c_sharp",
        "comment",
        "cpp",
        "css",
        "csv",
        "desktop",
        "diff",
        "dockerfile",
        "editorconfig",
        "elixir",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "html",
        "http",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "kotlin",
        "markdown",
        "lua",
        "luadoc",
        "luap",
        "make",
        "markdown",
        "markdown_inline",
        "mermaid",
        "nginx",
        "passwd",
        "poe_filter",
        "powershell",
        "printf",
        "properties",
        "query",
        "requirements",
        "regex",
        "rust",
        "scss",
        "sql",
        "ssh_config",
        "svelte",
        "toml",
        "tmux",
        "tsx",
        "typescript",
        "udev",
        "vim",
        "vimdoc",
        "xresources",
        "yaml",
        "zathurarc"
    },
    sync_install = true,
    -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
    auto_install = true,
    ignore_install = {},
    highlight = {
      enable = true,
      disable = {},
      additional_vim_regex_highlighting = false,
    },
}

