require'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "bash",
        "c",
        "css",
        "diff",
        "dockerfile",
        "fish",
        "gitcommit",
        "gitignore",
        "git_rebase",
        "html",
        "kotlin",
        "java",
        "javascript",
        "json",
        "lua",
        "markdown",
        "python",
        "query",
        "regex",
        "rust",
        "scss",
        "sparql",
        "sql",
        "svelte",
        "toml",
        "typescript",
        "vim",
        "vimdoc",
        "yaml"
    },
    sync_install = false,
    -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
    auto_install = true,
    ignore_install = {},
    highlight = {
      enable = true,
      disable = {},
      additional_vim_regex_highlighting = false,
    },
}

